name: Aggregation Service
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic to read data from
    defaultValue: ''
    required: true
  - name: redis_host
    inputType: FreeText
    description: External Redis hostname
    defaultValue: ''
    required: true
  - name: redis_port
    inputType: FreeText
    description: External Redis port
    defaultValue: ''
    required: true
  - name: redis_password
    inputType: Secret
    description: External Redis password
    defaultValue: redis_password
    required: true
dockerfile: build/dockerfile
runEntryPoint: main.py
defaultFile: main.py
